url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
library(data.table)
f <- file.path(getwd(), "data.zip")
download.file(url, f)
unzip(f)
setwd("UCI HAR Dataset")
x_test <- read.table("test/X_test.txt")
y_test <- read.table("test/Y_test.txt")
x_train <- read.table("train/X_train.txt")
y_train <- read.table("train/Y_train.txt")
x_merge <- rbind(x_test, x_train)
l = list(y_test, y_train)
y_merge <- rbindlist(l)
features <- read.table("features.txt")
colnames(x_merge) <- as.character(features[,2])
valid_column_names <- make.names(names=names(x_merge), unique=TRUE, allow_ = TRUE)
colnames(x_merge) <- valid_column_names
test_subject <- read.table("test/subject_test.txt")
train_subject <- read.table("train/subject_train.txt")
subject_merge <- rbind(test_subject, train_subject)
setnames(subject_merge, names(subject_merge), "Subject")
setnames(y_merge, names(y_merge), "Activity")
meanCols <-  grep("mean..",features$V2)
stdCols <-  grep("std..",features$V2)
extract <- subset(x_merge,select = c(meanCols,stdCols) )
act_label <- read.table("activity_labels.txt")
colnames(act_label) <- c("Activity", "ActivityName")
datav1 <- cbind(y_merge,subject_merge, x_merge)
datav2 <- merge(datav1, act_label, by = 'Activity', all.x = TRUE)
library(dplyr)
datav2melt <- melt(datav2, id = c("Activity", "Subject"))
nrow(datav2melt)
datav2melt$value <- as.numeric(datav2melt$value)
datav2cast <- dcast(datav2melt, Activity + Subject ~ variable, mean)
write.table(datav2cast, "tidy_data.txt", row.names = FALSE, quote = FALSE)
